### ISSUE TITLE
Nomenclature

### ISSUE THREAD

**Issue by LucasBHub** [CloudyOverhead/Gabarit_LaTeX_INRS#5]
While using \makenomenclature and \printnomenclature there is by default an entry which is : "INRS : Institut national de la recherché scientifique". However there is no where to be found a mention of \nomenclature{INRS}. Why does this appear and how to delete it ? Thanks

**Comment by CloudyOverhead** [comment]
Hi Lucas!

The nomenclature entry appears in [the Chapter 1 example](https://github.com/CloudyOverhead/Gabarit_LaTeX_INRS/blob/90f37b24c27d69a2a986b58c40e34b965174e8fa/chap1/chap1.tex#L6). It was present in the original version of the template and I have kept it to provide an example of how to use the `\nomenclature{*}{*}` syntax. If you wish to delete it, you just have to delete that line in particular.

I hope this proves useful. Please close this issue if this is satisfactory and tell me if I can help with anything else.

🚀
